version: '3'

services:
  platform:
    build: .
    ports:
      - '4000:4000'
    volumes:
      - .:/platform
    networks:
      - agri
  portal:
    build: ../agriworks_portal
    environment:
      AGRIWORKS_API_HOST: "platform"
    ports:
      - '8080:8080'
    volumes:
      - ../agriworks_portal:/portal
    networks:
      - agri

networks:
  agri: {}
