branch-defaults:
  master:
    environment: test
  PROD:
    environment: Agriworksproduction-env
environment-defaults:
  test:
    branch: null
    repository: null
global:
  application_name: agriworks
  default_ec2_keyname: agriworks
  default_platform: Python 3.6 running on 64bit Amazon Linux
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
  