version: 2.1

orbs:
  python: circleci/python@0.2.1

workflows:
  version: 2.1
  build:
    jobs:
      - deploy:
          context: agriworks
          filters:
            branches:
              only:
                - staging
                - master
                - circleci-project-setup


jobs:
  deploy:
    working_directory: /home/circleci/agriworks_platform
    docker:
      - image: circleci/python:3-node
    steps:
      - checkout

      - run:
          name: Deploying
          working_directory: /
          command: |
            # echo ${CREDS}
            printenv
            cd /home/circleci/
            git clone https://github.com/Hack4Impact-Boston-University/agriworks_portal
            cd agriworks_platform
            # pip3 install --user -r requirements.txt
            pip3 install --upgrade --user awsebcli
            # echo $CREDS > creds.yaml
            # ls -al
            # cat creds.yaml
            cd ../agriworks_portal && yarn install && cd ../agriworks_platform
            ./deploy.sh



