version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  deploy:
    working_directory: ~/app
    docker:
      - image: circleci/ruby:2.4.3
    steps:
      - checkout

      - run:
          name: Deploying
          working_directory: ~/app
          command: |
            ./deploy.sh
            ls

      # - run:
      #     name: Deploying
      #     command: eb deploy $CIRCLE_BRANCH-my-application

workflows:
  version: 2.1
  build:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - staging
                - master
                - circleci-project-setup
